---
- name: ensure libselinux-python and policycoreutils-python are installed (CentOS 7)
  package:
    name: libselinux-python,policycoreutils-python
    state: present
  when: ansible_distribution == 'CentOS' and ansible_distribution_version == '7'
  tags: selinux

- name: ensure policycoreutils-python-utils is installed (CentOS 8)
  package:
    name: policycoreutils-python-utils
    state: present
  when: ansible_distribution == 'CentOS' and ansible_distribution_version == '8'
  tags: selinux

- name: configure selinux policy and state
  selinux:
    conf: "{{ selinux_config|default('/etc/selinux/config') }}"
    policy: "{{ selinux_policy|default('targeted') }}"
    state: "{{ selinux_state|default('enforcing') }}"
  tags: selinux

- name: toggle selinux booleans
  seboolean:
    name: "{{ item.key }}"
    state: "{{ item.value.state|default('yes') }}"
    persistent: "{{ item.value.persistent|default('yes') }}"
  with_dict: "{{ selinux_boolean|default({}) }}"
  tags: selinux

- name: configure selinux network port definition
  seport:
    setype: "{{ item.key }}"
    ports: "{{ item.value.ports }}"
    proto: "{{ item.value.protocol|default('tcp') }}"
    state: "{{ item.value.state|default('present') }}"
  with_dict: "{{ selinux_ports|default({}) }}"
  tags: selinux

- name: configure selinux fcontext
  sefcontext:
    target: "{{ item.value.file_spec }}"
    ftype: "{{ item.value.ftype|default('a') }}"
    setype: "{{ item.value.setype }}"
    state: "{{ item.value.state }}"
  with_dict: "{{ selinux_fcontext|default({}) }}"
  tags: selinux
